# -*- coding: utf-8 -*-
from django.core.validators import MaxValueValidator, MinValueValidator

from helpers.tiradados import calcula


__author__ = 'peter'

from django.db import models


class Personaje(models.Model):
    #DATOS PERSONALES
    nombre = models.CharField(max_length=200)
    jugador = models.CharField(max_length=200, blank=True, null=True, default='')
    ocupacion = models.CharField(max_length=200, blank=True, null=True, default='')
    sexo = models.CharField(max_length=200, blank=True, null=True, default='')
    nacimiento = models.CharField(max_length=200, blank=True, null=True, default='')
    residencia = models.CharField(max_length=200, blank=True, null=True, default='')
    retrato = models.CharField(max_length=200, blank=True, null=True, default='')
    #CARACTERISTICAS
    FUE = models.PositiveSmallIntegerField(blank=True, null=True, default=calcula("3d6")*5, validators=[MaxValueValidator(100), MinValueValidator(15)])
    DES = models.PositiveSmallIntegerField(blank=True, null=True, default=calcula("3d6")*5, validators=[MaxValueValidator(100), MinValueValidator(15)])
    INT = models.PositiveSmallIntegerField(blank=True, null=True, default=calcula("2d6+6")*5, validators=[MaxValueValidator(100), MinValueValidator(35)])
    CON = models.PositiveSmallIntegerField(blank=True, null=True, default=calcula("3d6")*5, validators=[MaxValueValidator(100), MinValueValidator(15)])
    APA = models.PositiveSmallIntegerField(blank=True, null=True, default=calcula("3d6")*5, validators=[MaxValueValidator(100), MinValueValidator(15)])
    POD = models.PositiveSmallIntegerField(blank=True, null=True, default=calcula("3d6")*5, validators=[MaxValueValidator(100), MinValueValidator(15)])
    TAM = models.PositiveSmallIntegerField(blank=True, null=True, default=calcula("2d6+6")*5, validators=[MaxValueValidator(100), MinValueValidator(35)])
    EDU = models.PositiveSmallIntegerField(blank=True, null=True, default=calcula("3d6+3")*5, validators=[MaxValueValidator(150), MinValueValidator(30)])
    MOV = models.PositiveSmallIntegerField(default=9)
    edad = models.PositiveSmallIntegerField(blank=True, null=True, default=EDU.default/5+6)
    #CARACTERISTICAS DERIVADAS
    cor = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    suerte = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    pv = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    pm = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    ph = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    pi = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    bd = models.CharField(max_length=200, blank=True, null=True, default='')
    com = models.CharField(max_length=200, blank=True, null=True, default='')
    #HABILIDADES
    antropologia = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    fusilescopeta = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    armacorta = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    armaf1 = models.CharField(max_length=200, blank=True, null=True, default='')
    armaf1val = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    arqueologia = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    arte1 = models.CharField(max_length=200, blank=True, null=True, default='')
    arte1val = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    arte2 = models.CharField(max_length=200, blank=True, null=True, default='')
    arte2val = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    arte3 = models.CharField(max_length=200, blank=True, null=True, default='')
    arte3val = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    buscarlibros = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    cerrajeria = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    charlataneria = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    ciencia1 = models.CharField(max_length=200, blank=True, null=True, default='')
    ciencia1val = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    ciencia2 = models.CharField(max_length=200, blank=True, null=True, default='')
    ciencia2val = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    ciencia3 = models.CharField(max_length=200, blank=True, null=True, default='')
    ciencia3val = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    cienciasocultas = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    conducirautomovil = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    conducirmaquinaria = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    contabilidad = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    credito = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    derecho = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    descubrir = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    discrecion = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    disfrazar = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    electricidad = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    encanto = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    equitacion = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    escuchar = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    esquivar = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    historia = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    historianatural = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    intimidar = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    lanzar = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    lengua1 = models.CharField(max_length=200, blank=True, null=True, default='')
    lengua1val = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    lengua2 = models.CharField(max_length=200, blank=True, null=True, default='')
    lengua2val = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    lengua3 = models.CharField(max_length=200, blank=True, null=True, default='')
    lengua3val = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    lenguaprop = models.CharField(max_length=200, blank=True, null=True, default='')
    lenguapropval = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    lucha = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    lucha1 = models.CharField(max_length=200, blank=True, null=True, default='')
    lucha1val = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    lucha2 = models.CharField(max_length=200, blank=True, null=True, default='')
    lucha2vaL = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    mecanica = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    medicina = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    mitosdecthulhu = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    nadar = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    orientacion = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    persuasion = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    pilotar = models.CharField(max_length=200, blank=True, null=True, default='')
    pilotarval = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    prestidigitacion = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    primerosauxilios = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    psicoanalisis = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    psicologia = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    saltar = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    seguirrastros = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    supervivencia = models.CharField(max_length=200, blank=True, null=True, default='')
    supervivenciaval = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    tasar = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    trepar = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    sonar = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    saberonirico = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    hab1 = models.CharField(max_length=200, blank=True, null=True, default='')
    hab1val = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    hab2 = models.CharField(max_length=200, blank=True, null=True, default='')
    hab2val = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    hab3 = models.CharField(max_length=200, blank=True, null=True, default='')
    hab3val = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    #ARMAS
    arma1 = models.CharField(max_length=200, blank=True, null=True, default='')
    arma1val = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    arma1danio = models.CharField(max_length=200, blank=True, null=True, default='')
    arma1alcance = models.CharField(max_length=200, blank=True, null=True, default='')
    arma1ataques = models.CharField(max_length=200, blank=True, null=True, default='')
    arma1municion = models.CharField(max_length=200, blank=True, null=True, default='')
    arma1fallo = models.CharField(max_length=200, blank=True, null=True, default='')
    arma2 = models.CharField(max_length=200, blank=True, null=True, default='')
    arma2val = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    arma2danio = models.CharField(max_length=200, blank=True, null=True, default='')
    arma2alcance = models.CharField(max_length=200, blank=True, null=True, default='')
    arma2ataques = models.CharField(max_length=200, blank=True, null=True, default='')
    arma2municion = models.CharField(max_length=200, blank=True, null=True, default='')
    arma2fallo = models.CharField(max_length=200, blank=True, null=True, default='')
    arma3 = models.CharField(max_length=200, blank=True, null=True, default='')
    arma3val = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    arma3danio = models.CharField(max_length=200, blank=True, null=True, default='')
    arma3alcance = models.CharField(max_length=200, blank=True, null=True, default='')
    arma3ataques = models.CharField(max_length=200, blank=True, null=True, default='')
    arma3municion = models.CharField(max_length=200, blank=True, null=True, default='')
    arma3fallo = models.CharField(max_length=200, blank=True, null=True, default='')
    arma4 = models.CharField(max_length=200, blank=True, null=True, default='')
    arma4val = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    arma4danio = models.CharField(max_length=200, blank=True, null=True, default='')
    arma4alcance = models.CharField(max_length=200, blank=True, null=True, default='')
    arma4ataques = models.CharField(max_length=200, blank=True, null=True, default='')
    arma4municion = models.CharField(max_length=200, blank=True, null=True, default='')
    arma4fallo = models.CharField(max_length=200, blank=True, null=True, default='')
    arma5 = models.CharField(max_length=200, blank=True, null=True, default='')
    arma5val = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    arma5danio = models.CharField(max_length=200, blank=True, null=True, default='')
    arma5alcance = models.CharField(max_length=200, blank=True, null=True, default='')
    arma5ataques = models.CharField(max_length=200, blank=True, null=True, default='')
    arma5municion = models.CharField(max_length=200, blank=True, null=True, default='')
    arma5fallo = models.CharField(max_length=200, blank=True, null=True, default='')
    #TRASFONDO
    descripcion = models.CharField(max_length=200, blank=True, null=True, default='')
    ideologia = models.CharField(max_length=200, blank=True, null=True, default='')
    gente = models.CharField(max_length=200, blank=True, null=True, default='')
    lugares = models.CharField(max_length=200, blank=True, null=True, default='')
    posesiones = models.CharField(max_length=200, blank=True, null=True, default='')
    rasgos = models.CharField(max_length=200, blank=True, null=True, default='')
    heridas = models.CharField(max_length=200, blank=True, null=True, default='')
    fobias = models.CharField(max_length=200, blank=True, null=True, default='')
    tomos = models.CharField(max_length=200, blank=True, null=True, default='')
    seres = models.CharField(max_length=200, blank=True, null=True, default='')
    #EQUIPO
    equipo = models.CharField(max_length=200, blank=True, null=True, default='')
    #DINERO
    recursos = models.CharField(max_length=200, blank=True, null=True, default='')
    efectivo = models.CharField(max_length=200, blank=True, null=True, default='')
    bienes = models.CharField(max_length=200, blank=True, null=True, default='')
    #COMPAÑEROS
    compa1 = models.CharField(max_length=200, blank=True, null=True, default='')
    compa1jug = models.CharField(max_length=200, blank=True, null=True, default='')
    compa2 = models.CharField(max_length=200, blank=True, null=True, default='')
    compa2jug = models.CharField(max_length=200, blank=True, null=True, default='')
    compa3 = models.CharField(max_length=200, blank=True, null=True, default='')
    compa3jug = models.CharField(max_length=200, blank=True, null=True, default='')
    compa4 = models.CharField(max_length=200, blank=True, null=True, default='')
    compa4jug = models.CharField(max_length=200, blank=True, null=True, default='')
    compa5 = models.CharField(max_length=200, blank=True, null=True, default='')
    compa5jug = models.CharField(max_length=200, blank=True, null=True, default='')
    compa6 = models.CharField(max_length=200, blank=True, null=True, default='')
    compa6jug = models.CharField(max_length=200, blank=True, null=True, default='')
    compa7 = models.CharField(max_length=200, blank=True, null=True, default='')
    compa7jug = models.CharField(max_length=200, blank=True, null=True, default='')
    compa8 = models.CharField(max_length=200, blank=True, null=True, default='')
    compa8jug = models.CharField(max_length=200, blank=True, null=True, default='')

    def __unicode__(self):
        return self.nombre

    class Meta:
        ordering = ('nombre',)
        verbose_name_plural = "Personajes"
        app_label = 'cthulhu'
